# Generated by Django 3.1.4 on 2020-12-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('in_progress', 'Заказ в обработке')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
